version: '3.9'

services:
    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: symfony-php
        volumes:
            - ./symfony:/var/www/symfony
        depends_on:
            - db

    nginx:
        image: nginx:1.25
        container_name: symfony-nginx
        ports:
            - "8080:80"
        volumes:
            - ./symfony:/var/www/symfony
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php

    db:
        image: postgres:16
        container_name: symfony-db
        environment:
            POSTGRES_DB: symfony
            POSTGRES_USER: symfony
            POSTGRES_PASSWORD: secret
        ports:
            - "5432:5432"
        volumes:
            - db_data:/var/lib/postgresql/data

volumes:
    db_data:
